# Generated by Django 5.2.8 on 2025-11-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Check this to display this product in the 'Featured Collection' on the Homepage."),
        ),
    ]
