"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Path to NPM for Tailwind CSS (This is for your local machine only)
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lqvrkd=9*nuhyxm%kxd@j-zh@pwo)@x*o(tqf+q6mb=lw1%ji$'

# SECURITY WARNING: don't run with debug turned on in production!
# On the server, you can change this to False later.
DEBUG = True

# --- DEPLOYMENT FIX 1: ALLOW HOSTS ---
# ['*'] allows the site to run on any domain (localhost or pythonanywhere)
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # --- JAZZMIN (Must be at the top) ---
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party
    'tailwind',
    'theme',
    'django_browser_reload', # Needed for Tailwind hot reload

    # Local Apps
    'store',
    'accounts',
]

# This tells django-tailwind which app holds the theme
TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Tailwind Reload Middleware
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'store', 'templates')], # Ensure template dir is found
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dress_shop_db',  # The database name
        'USER': 'root',           # Your MySQL username
        'PASSWORD': 'root',       # Your MySQL password
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# --- DEPLOYMENT FIX 2: STATIC ROOT ---
# This tells Django where to collect files when running on the server
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Authentication Redirects ---
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# --- Tailwind Internal IPs ---
INTERNAL_IPS = [
    "127.0.0.1",
]

# --- RAZORPAY SETTINGS ---
RAZORPAY_KEY_ID = 'rzp_test_RhW4po3GhDXdsq'
RAZORPAY_KEY_SECRET = 'CJmGwBBCmke3Hvpg1XC9uhCI'

# --- PAYMENT MASTER SWITCH ---
# Set to True for Free Hosting / Demo
# Set to False for Live Site (Requires HTTPS & Paid Plan)
PAYMENT_SIMULATION_MODE = True

# --- EMAIL CONFIGURATION ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nooras.official@gmail.com'
EMAIL_HOST_PASSWORD = 'dhjw pzko vgvg wuxh'


# --- JAZZMIN SETTINGS (Admin Theme) ---
JAZZMIN_SETTINGS = {
    "site_title": "Noora's Admin",
    "site_header": "Noora's Ladies Wear",
    "site_brand": "Noora's Admin",
    "welcome_sign": "Welcome to Noora's Dashboard",
    "copyright": "Noora's Ladies Wear",
    "search_model": ["store.Order", "store.Product"],

    # Top Menu
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "home", "new_window": True},
    ],

    # Sidebar Layout
    "order_with_respect_to": [
        "store.Order",
        "store.Product",
        "store.ProductVariant",
        "store.Category",
        "auth"
    ],

    # Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "store.Product": "fas fa-tshirt",
        "store.Category": "fas fa-layer-group",
        "store.Order": "fas fa-shopping-bag",
        "store.CartItem": "fas fa-shopping-cart",
        "store.ProductVariant": "fas fa-boxes",
        "store.Size": "fas fa-ruler",
        "store.Color": "fas fa-palette",
        "store.ProductImage": "fas fa-images",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}